### ISSUE TITLE
Do we want to remove multiIndex from the df_lc data structure in light curves notebook?

### ISSUE THREAD

**Issue by jkrick** [nasa-fornax/fornax-demo-notebooks#159]
If the reason for having the multiIndex set on the df_lc is to use in the ML notebook, but the ML notebooks get rid of them right away, should we also remove them from the light curve notebook?

What I can see upfront as the work involved here:
- they are set in all of the get_lightcurves functions, but this should be relatively easy to remove, ie., not set
- plotting function uses them so that would need to be re-written to remove the indices.
- would effect @xoubish ML_AGNzoo.ipynb - not sure of the impact here.
- Would removal of indices mean that we no longer need the multi index df class?

This should certainly wait for issue #158 to be done.

**Comment by jkrick** [comment]
Removing the multi index might be helpful in thinking about scaling up the light curves even further to out of memory operations.  More research is needed into wether or not dask can work with multi index pandas, or if the indices must be reset before using dask anyway.

**Comment by troyraen** [comment]
> Do we want to remove multiIndex from the df_lc data structure in light curves notebook?

I vote "yes". I think we should get rid of the multi-index altogether. See my https://github.com/fornax-navo/fornax-demo-notebooks/pull/151#pullrequestreview-1649855474 for more detail.

> Would removal of indices mean that we no longer need the multi index df class?

I vote to get rid of this as well (`MultiIndexDFObject` -- and it actually does very little w.r.t. the index anyway). If #155 goes through, the only stuff left there will be `append` and `remove` which are both easily handled by native pandas methods so it would be better IMO to just use pandas directly.

I agree that #158 will be a good test case and should go first.

**Comment by jkrick** [comment]
I am going to close this for now, we haven't done anything about it in 10 months, and I think touching the light curve notebook this late in the game doesn't make sense for a somewhat incremental change.  If we choose at some point to think about out of memory scaling for the light curve notebook, we are going to want to experiment with dask and then we can come at this topic from that perspective. LINCC is currently pushing nested dask data frames.
