### ISSUE TITLE
ERROR: `pip` reports `boto3`/`botocore` version conflict

### ISSUE THREAD

**Issue by troyraen** [nasa-fornax/fornax-demo-notebooks#262]
@jkrick reported that running `!pip install -r requirements.txt` in the 'light_curves' directory can give the following error:

```
ERROR: pip's dependency resolver does not currently take into account all the
packages that are installed. This behaviour is the source of the following
dependency conflicts.
boto3 1.29.3 requires botocore<1.33.0,>=1.32.3, but you have botocore 1.34.51
which is incompatible.
```

_Originally posted by @jkrick in https://github.com/fornax-navo/fornax-demo-notebooks/pull/215#discussion_r1537905804_

@bsipocz commented:

> hmm, should we suggest pip install -U -r requirements.txt, or to work from a clean environment first and only run the install at the first time? I'm not exactly sure, but am rather certain these types of issues will pop up for users all the time

**Comment by troyraen** [comment]
Reporting that I also see this error on `irsakusp` using the kernel 'Python 3 (ipykernel)'.

**Comment by bsipocz** [comment]
I suppose we better not install it in the notebooks, but include in all the images instead? That may be the reason that the problem has gone away, as @zoghbi-a has some image updates since this issue was opened.

**Comment by troyraen** [comment]
Sounds like we can close this then.
