### ISSUE TITLE
TQDM for notebooks

### ISSUE THREAD

**Issue by bsipocz** [nasa-fornax/fornax-demo-notebooks#297]
@delucchi-cmu mentioned there is a solution for a progress bar that doesn't dump rubbish to into the notebook/rendering

**Comment by delucchi-cmu** [comment]
We experienced the same issue with our sphinx/html-rendered. You can follow some of the solution in this issue: https://github.com/astronomy-commons/lsdb/issues/167

tl;dr:

- add `ipywidgets` dependency
- change import statements: `from tqdm import tqdm` -> `from tqdm.auto import tqdm`
