### ISSUE TITLE
BUG: ztf_functions.py should be importable even when there is no access permission to the s3 bucket

### ISSUE THREAD

**Issue by zoghbi-a** [nasa-fornax/fornax-demo-notebooks#332]
ztf_functions.py [accesses a remote bucket during import](https://github.com/nasa-fornax/fornax-demo-notebooks/blob/0434f1e25390a90f5544f3d39c3179f2ca5b0661/light_curves/code_src/ztf_functions.py#L22). This is probably not a good idea as it prone to failure when the permission to the bucket is not setup correctly.

**Comment by bsipocz** [comment]
This problem has already been captured in https://github.com/nasa-fornax/fornax-demo-notebooks/issues/311. Note, the ZTF access issue cannot be remedied yet as it is not yet have an ODR place.

I would go ahead and close this as a duplicate, but if you have an idea for a suitable workaround, feel free to reopen (I don't think it's any particularly useful to skip ZTF and yet create the light curves when there is no access to the bucket as in practice that dataset is heavily used in all the follow-up notebooks).

**Comment by bsipocz** [comment]
OK, that makes a lot of sense, reopening it for tracking the python script importability rather than the bucket issue.

**Comment by troyraen** [comment]
@bsipocz is it ok if I fix this? This module uses multiprocessing internally which complicates this a bit, but I think I see how to lazy load that variable in an efficient way.

**Comment by bsipocz** [comment]
Sure! I was only planning to move the quoted line into a function body, so it's not touched at import time, but anything would work really.
