### ISSUE TITLE
render notebooks

### ISSUE THREAD

**Issue by jkrick** [nasa-fornax/fornax-demo-notebooks#58]
issue copied from Brigitta from older repository:

While CI executing the notebook maybe a stretch goal given the non-triviality of installing dependencies rendering executed notebooks to HTML and hosting those on e.g. RTD/gh-pages shouldn't be too difficult using the infrastructure I set up for e.g. the astroML notebooks.

**Comment by bsipocz** [comment]
I move the rendering of the notebooks to a separate repo, so it will be super clean and clear of what are the deployed notebooks.

I also propose doing the markdown formatting for them, even if we don't switch for this particular repo (see #36)

**Comment by bsipocz** [comment]
I would close this now, we do have rendering and for a subset also executed rendering.
